# Generated by Django 3.2.11 on 2022-02-02 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_setting_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='realtor_id',
            new_name='realtor',
        ),
    ]
